name: HealthOverHead
author: CookieCode
api: [3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-A3.0.0-ALPHA10]
version: 1.2
main: HealthOverHead\Main
commands:
 healthoverhead:
  description: Developper information.
  aliases: [hoh]
  permission: hoh.info
permissions:
 hoh.info:
  description: "Developper information."
  default: true
